### PR TITLE
Overhaul ACPI hooks concerning sound

### PR DESCRIPTION
**Pull request by ehegnes**
See issue #113 for more information.

### CODE REVIEW

**Comment by ianwalter** [comment]
Here's the output from running sound.sh:
```
Setting sound card UCM verb...
Home directory not accessible: Permission denied
Restoring asla config...
Setting up ACPI hooks...
ACPI hooks successfully installed.
!! Please remove all previously configured hooks that recognize `jack/headphone`.
Sound setup completed successfully.
```
Not sure where `Home directory not accessible: Permission denied` comes from, I don't see anything that would cause that in the script and it gives that output if I run `sound.sh` on master as well.

I no longer get the `Headphones may not work correctly!` from running `sound.sh` as I do on master, but automatic switching between headphones and speakers still doesn't work and now I have the problem where headphone volume is really low again. I had previously fixed that by running `sudo alsactl restore --file alsa/headphones.state` however this reverses the channels on the speakers for some reason.

I didn't do anything to "remove all previously configured hooks that recognize `jack/headphone`." because I don't know what this entails.

**Comment by ehegnes** [comment]
That home directory error is very strange...can you post an [`strace`](https://github.com/bnoordhuis/strace) log (`strace -o log.strace ./sound.sh`)? You may have to be root to run that command successfully.

I haven't looked into the usage of the ALSA `*.state` files. I'll look into this ‒ it may be beneficial to incorporate these into the ACPI hooks.

As far as removing "all previously configured hooks that recognize `jack/headphone`" is concerned, I could probably elaborate more on this. My tweaks to the ACPID conf makes obsolete any event handling of `jack/headphone` in `/etc/acpi/handler.sh`. I *could* programmatically delete this (which is left over from the previous `sound.sh` script), but hopefully @nelsonni will write an ACPID overhaul that will nuke these existing configs.

Thanks, @ianwalter, for your testing and contributions!

**Comment by ianwalter** [comment]
I ran strace and it said this:
```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```
Not sure why it says that but I don't get the permission denied message anymore (previously I had tried the script with sudo and it still gave me the permission denied message). 

I don't have a `handler.sh` in `/etc/acpi` by the way. 

Thank you and feel free to ping me for any further testing.

**Comment by mjrosencrantz** [comment]
Thanks!

It almost works.  There was no matching directory in tmp for me.  The directory it needed to find was /run/user/1000/pulse.  I just set that manually instead of doing the $(find ...) and everything worked.  One possibility is that something is setting XDG_RUNTIME_DIR in my env.  If this is common to most distributions perhaps you could grab it when sound.sh is run and add it to the shamus.sh script during install.

I also got the home directory error.  It's because you are running the command:

ALSA_CONFIG_UCM=ucm/ alsaucm -c bdw-rt5677 set _verb HiFi

as root.  Previously it was not run under sudo.  I'm not exactly sure what is being accessed, but I think you might have to go back to the "sudo on almost every line" thing.

Thanks again for doing this!

**Comment by ehegnes** [comment]
@mjrosencrantz I was concerned that that maybe not everybody had a tmp directory as their `PULSE_RUNTIME_PATH`. I'll add the original checks to find it in `/run/user/`. Thanks for pinpointing the problem with `sudo`. I see no need to go back to using `sudo` on every line. Can you try replacing 

```shell
ALSA_CONFIG_UCM=ucm/ alsaucm -c bdw-rt5677 set _verb HiFi
```

with

```shell
su $SUDO_USER -c "ALSA_CONFIG_UCM=ucm/ alsaucm -c bdw-rt5677 set _verb HiFi"
```
and see if demoting privileges works in that way?

@ianwalter don't worry about `strace` since @mjrosencrantz found the issue. Also, I suspect (hope) that your issue is in finding the proper `PULSE_RUNTIME_PATH`. We'll see if my next update to this fixes audio for you too.

**Comment by raphael** [comment]
Thanks for all the work @ehegnes ! I'll wait until you resolve the issues above before merging.

**Comment by mjrosencrantz** [comment]
> su $SUDO_USER -c "ALSA_CONFIG_UCM=ucm/ alsaucm -c bdw-rt5677 set _verb HiFi"

This worked for me.

Thanks!

**Comment by ehegnes** [comment]
I finally got around to adding the original runtime path finder in case my finder doesn't properly work. Sound switching should work for everybody with whom it originally worked.

It may make sense to read the `pulseaudio` source code in the future and possibly use `XDG_RUNTIME_PATH` as @mjrosencrantz mentioned. I glanced at the source. `PULSE_RUNTIME_PATH` (the culprit, it seems, in obtaining cross-distro compatibility) is pretty much set at build time. I haven't bothered checking how various distros like to do this yet.

@ianwalter I'm intrigued by your persisting sound issues. What distro are you running? Is `XDG_RUNTIME_PATH` set in your env? Do you have a path such as `/run/user/$(id -u $USER)/pulse/`?

@raphael, you created those `{headphones,speakers}.state` files. Should the ACPI hook have `alsactl` load these after switching the input? Apparently this fixes relative volumes, but it reverses output channels?

**Comment by raphael** [comment]
I'm not sure if loading the alsa states is necessary. I had created these files by capturing the state in ChromeOS hoping that it would help reproduce the same settings in Linux but I'm not sure it's working well.

**Comment by ianwalter** [comment]
I am running Ubuntu 15.10 and `$XDG_RUNTIME_PATH` does not appear to be set but I do have `/run/user/1000/pulse/`.

**Comment by raphael** [comment]
What is the status of this PR? sounds like more work is needed?

**Comment by ehegnes** [comment]
I haven't touched this in a while. It *should* work as a replacement for the current scripts, improving compatibility with different ACPID installs due to the way it configures it. Essentially, it doesn't rely on `sed` needing a certain exact configuration file (/etc/acpi/handler.sh) to produce a proper config. But I wasn't able to fix the issue ianwalter was having.

**Comment by nskaggs** [comment]
As 15.10 is EOL next month anyway, I would simply ensure this works on xenial and perhaps trusty. It would be good to improve the sound situation overall as the script is fragile. [Getting proper support would be best](https://bugs.chromium.org/p/chromium/issues/detail?id=573776).

**Comment by raphael** [comment]
Can anyone confirm whether the scripts work on Xenial and/or Trusty? Would like to get this merged (testing on ArchLinux)

**Comment by gwillem** [comment]
It works smoothly with Xenial / Xubuntu 16.04. Thanks a lot @ehegnes!

With `set -x`:
```
# bash sound.sh 
+ PROMPT=sudo
+ '[' 0 -eq 0 ']'
+ '[' -d /lib/firmware ']'
+ cp -r ../../../firmware/en_us.mmap ../../../firmware/intel ../../../firmware/iwlwifi-7260-16.ucode ../../../firmware/rt5677_elf_vad /lib/firmware
+ cp modprobe.d/alsa-bdwrt5677.conf /etc/modprobe.d
+ echo 'Setting sound card UCM verb...'
Setting sound card UCM verb...
+ su willem -c 'ALSA_CONFIG_UCM=ucm/ alsaucm -c bdw-rt5677 set _verb HiFi'
+ '[' '!' 0 -eq 0 ']'
+ egrep -q '^[    ]*load-module module-alsa-source device=hw:1,1' /etc/pulse/default.pa
+ '[' 1 -eq 0 ']'
+ egrep -q '^[    ]*load-module module-alsa-source device=hw:1,2' /etc/pulse/default.pa
+ '[' 1 -eq 0 ']'
+ egrep -q '^[    ]*load-module module-alsa-source device=hw:0,1' /etc/pulse/default.pa
+ egrep -q '^[    ]*load-module module-alsa-source device=hw:0,2' /etc/pulse/default.pa
+ alreadyset=0
+ '[' '!' 0 -eq 0 ']'
+ echo 'Restoring asla config...'
Restoring asla config...
+ alsactl restore --file alsa/speakers.state
+ alsactl store
+ echo 'Setting up ACPI hooks...'
Setting up ACPI hooks...
+ ACPID_DIR=/etc/acpi
+ '[' '!' -d /etc/acpi ']'
+ cp -r actions events /etc/acpi/
+ '[' 0 -eq 0 ']'
+ echo 'ACPI hooks successfully installed.'
ACPI hooks successfully installed.
+ echo -e '\e[93m!! Please remove all previously configured hooks that recognize `jack/headphone`.\e[0m'
!! Please remove all previously configured hooks that recognize `jack/headphone`.
+ echo 'Sound setup completed successfully.'
Sound setup completed successfully.
+ exit 0
```

**Comment by ehegnes** [comment]
Welcome @gwillem! :)

This has actually been ready for merge for a while — I was just hoping it would have solved some problems that others were experiencing. Regardless, it's a cleaner way to implement ACPI hooks.

I was about to write on how users should probably clean their `/etc/acpi/handler.sh` file from the previous script version, but thinking on it now, the new setup will intercept the plugging events and halt their propagation to `handler.sh`, so this isn't mandatory. Should the user be notified that they *may* clean `handler.sh` anyway?

**Comment by raphael** [comment]
OK merging then, thank you @ehegnes ! We could add a note to the README about the optional cleanup although that doesn't seem crucial :)

**Pull request merged**
