### PR TITLE
Kernel config changes

### PR DESCRIPTION
**Pull request by ehegnes**
`bulid/linux/.config` used to be a symlink to `scripts/config`. I have swapped this arrangement to improve ease of configuration with `menuconfig` and `nconfig`.

More comprehensive file system support is built into the kernel image to improve compatibility without the use of `initrd` or `initramfs`.

@raphael, please feel free to make these changes yourself if a PR is not the most convenient way to integrate. I don't know what your build process is like.

### CODE REVIEW

**Comment by raphael** [comment]
Just wondering what issue you see with the symlink? The config is used in a number of places (e.g. to build the AUR package as well) and I have all these places pointing to "the one true" config in the scripts folder. The entire "build" folder gets wiped out during the release process so putting it there means I need to adjust the other symlinks and my release procedure. The only issue I'm aware of is that I need to copy back the file to the scripts directory and rebuild the symlink when I modify the config but that happens rarely and by now is a fairly standard procedure (to me). Long story short do you think you could leave the symlink as is and change the file in the scripts folder instead? Thank you!

**Comment by ehegnes** [comment]
I don't really have an issue with it. When I run `make menuconfig`, it replaces the symlink with a file. My copying the file over to the scripts folder and replacing the symlink really isn't a big deal, as you describe. It sounds like your symlink paradigm is quite well justified. I shall do as you suggested.

**Comment by raphael** [comment]
Awesome, thank you!

**Comment by raphael** [comment]
I've released 4.4-4 with these changes.

**Pull request merged**
