### PR TITLE
README improvements + IRC shield

### PR DESCRIPTION
**Pull request by ethanmad**
The commit messages are pretty descriptive, so please read those for the content of this PR.

There are two things worth discussing before merging this:

1. Line breaks in the README. There document was more-or-less hard-wrapped at 80 characters, so I made that more consistent throughout in b80822b. However, this ruins blame and makes the commit change many more lines than necessary. Also, if/when sentences get reworded in the future, the breaks will move again, so we'll have the same problem down the road. I prefer doing one sentence per line as in https://github.com/spf13/hugo/commit/5cf1475ecd72a2f17c7ec48ccf499b2e3a5f49b4 as it seems better for Git (alternatively, soft-wrapping is an option that I'm sure was previously considered).
Maybe we should skip the line break changes altogether to preserve blame.

2. Community section. First of all, where should the section go in the README? Many projects put their Gitter/whatever badges at the top (we could use a badge like chatbadge at the top), but I chose to put the section at the bottom because the top of the README is so well put together and the Community fits well with Contributions.

Is #Pixel2015 the channel name we want to use? Is IRC the best platform for external discussion?

Should I squash these commits?

Please give some feedback and I'll fix things up.

### CODE REVIEW

**Comment by ehegnes** [comment]
Firstly, I vote for a badge, as mentioned, at the top of the README -- it doesn't take up much space, and it provides people with an immediate sense of support when looking to troubleshoot.

I personally like hard-wraps at ~80 chars, but there is no guarantee that people contributing in the future will conform to this...eh, I really don't have much of an opinion on this.

As far as the IRC (yes, I think this the best medium) channel is concerned, maybe `#linux-samus` or some variant would be more descriptive, since `#Pixel2015` may be misinterpreted as a general discussion channel instead of one dealing directly with this project.

I, myself, wouldn't squash. You have two commits that have two well-defined and distinctive goals, regardless of the fact that they operate on the same file.

**Comment by ethanmad** [comment]
I've registered `#linux-samus`. I'll wait for @raphael's comments before editing, but I agree with most of your comments, @ehegnes.

**Comment by raphael** [comment]
Thank you for putting this together! looks great. I don't have a strong opinion on how to format the README. Diffs are fairly easy to scan anyway. I like #linux-samus for the irc channel name and agree with @ehegnes with putting the badge at the top. Just curious: why choose IRC instead of e.g. gitter? or slack? probably more a question of habit but I haven't used IRC in quite a long time. We could create a linux-samus slack channel.

**Comment by ehegnes** [comment]
I use IRC because I've been too ignorant to try those alternative that you've listed. I also use it for other (mostly Linux related) chats, and it doesn't require any specific windowing toolkit.

Slack is closed source and doesn't support open registration without messy workarounds. As far as I can tell, it is more for team-based chats rather than widely available troubleshooting.

I don't know much about Gitter. It does seem to be utilizable via IRC clients...

**Comment by colemickens** [comment]
Matrix is an option. Open source. Interop with IRC: http://matrix.org/docs/projects/try-matrix-now.html

Slack leaves a bad taste in my mouth as well. Between it being closed-source, the quality of the IRC bridge, and the one-account-for-every-chatroom model, I'm not a huge fan of Slack.

**Comment by raphael** [comment]
OK sounds like the majority votes IRC :) what client do you guys use?

**Comment by nelsonni** [comment]
I also prefer IRC for it's open nature and extensible clients. I just use Polari because I rarely need more features.

**Comment by raphael** [comment]
As long as I can slap people around with a big trout it's all good.

**Comment by ehegnes** [comment]
@colemickens Matrix looks quite appealing!

@raphael I use [`irssi`](https://irssi.org/), but I don't recommend it. A lot of people like [`WeeChat`](http://weechat.org/), methinks.

**Comment by ethanmad** [comment]
I'm OK with gitter, but I don't think Slack is the right fit. Matrix looks
cool from what I saw, but I didn't give it a good look. To me, IRC is nice
because it's so open and requires minimal setup. Plus, there are relevant
channels on freenode. I use WeeChat as my IRC client and like it (but I
haven't used many others).

@raphael, I think we can all agree to give you a big trout to slap us with
no matter what platform we use.

If anyone here would like to use my ZNC server as a bouncer (to stay logged
in), let me know. It can *probably* handle a few more people.

**Comment by ethanmad** [comment]
I revised the commits. A few changes from the old versions: 

In 8cd78d5:

* All references to "Pixel 2" have been changed to "Pixel 2015" (following the header's example).
* There's a link to the AUR package.

In 9cff40d:

* There is now a "shield" linking to `#linux-samus` on freenode.net, like [Chat with us on #linux-samus on freenode.net](https://webchat.freenode.net/?channels=linux-samus "Chat with us on #linux-samus on freenode.net"). (Color and text can be changed by editing the image URL.) I made the text and hover text fairly descriptive, so...
* The Community section has been removed.

Anything else to change before merging?

**Comment by raphael** [comment]
LGTM, thanks!

**Pull request merged**
