### PR TITLE
OpenRC Addition

### PR DESCRIPTION
**Pull request by ehegnes**
These commits add setup scripts to integrate with the OpenRC init system. The README is updated as appropriate. The original touchpad setup script is also renamed to `setup.xinitrc.sh` so as to adopt a descriptive name like `setup.openrc.sh` and `setup.systemd.sh`.

### CODE REVIEW

**Comment by ehegnes** [comment]
Oops, I didn't realize that wulvyrn's changes to README haven't yet been merged. Please merge that before this -- I'll rebase.

**Comment by raphael** [comment]
Thanks! I've merged the other PR.

**Comment by ehegnes** [comment]
Finally got around to rebasing. This is ready to be merged. :)

**Comment by raphael** [comment]
Awesome, thanks!

**Pull request merged**
