### PR TITLE
touch pad systemd service and brightness systemd service

### PR DESCRIPTION
**Pull request by wulvyrn**
this provides a script to copy and enable the brightness service and scripts.

this provides a systemd trackpad service which seems to be working.
.xinitrc did not work under testing.  systemd did work with a few modifications.

### CODE REVIEW

**Comment by raphael** [comment]
This is great, thank you!

**Comment by raphael** [comment]
Could I convince you to update the content of the README with these changes?

**Comment by wulvyrn** [comment]
I will work on that tomorrow.

**Comment by raphael** [comment]
Awesome, thank you!

**Pull request merged**
